package store
import("context";"encoding/json";"time";"github.com/shido-ui/Worldbuster/backend/internal/simulation")
type SimulationMemoryRecord struct{ID string;CharacterID string;MemoryType string;TargetID string;Event string;Importance int;Sentiment int;CreatedAt time.Time}
type SimulationActionRecord struct{ID string;CharacterID string;ActionType string;TargetID string;DecisionScore int;Executed bool;CreatedAt time.Time}
type SimulationRepository struct{DB *DB}
func(r SimulationRepository)EnsureCharacter(ctx context.Context,c simulation.SimCharacter)error{personality,_:=json.Marshal(c.Personality);goals,_:=json.Marshal(c.Goals);_,err:=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_characters(character_id,name,controller_type,personality,goals,last_tick,active) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(character_id) DO UPDATE SET name=EXCLUDED.name,personality=EXCLUDED.personality,goals=EXCLUDED.goals,last_tick=EXCLUDED.last_tick,active=EXCLUDED.active",c.ID,c.Name,string(c.Controller),personality,goals,c.LastTick,c.Active);return err}
func(r SimulationRepository)RecordMemory(ctx context.Context,characterID string,m simulation.Memory)error{_,err:=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_character_memory(character_id,memory_type,target_id,event,importance,sentiment,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)",characterID,m.Type,m.TargetID,m.Event,m.Importance,m.Sentiment,m.CreatedAt);return err}
func(r SimulationRepository)RecordAction(ctx context.Context,characterID string,a simulation.Action,executed bool)error{_,err:=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_character_actions(character_id,action_type,target_id,decision_score,executed) VALUES($1,$2,$3,$4,$5)",characterID,string(a.Type),a.TargetID,a.Priority,executed);return err}
func(r SimulationRepository)RecordRelationship(ctx context.Context,rel simulation.Relationship)error{_,err:=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_relationships(character_id,target_id,affinity,trust,familiarity,interactions,last_interaction,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,NOW()) ON CONFLICT(character_id,target_id) DO UPDATE SET affinity=EXCLUDED.affinity,trust=EXCLUDED.trust,familiarity=EXCLUDED.familiarity,interactions=EXCLUDED.interactions,last_interaction=EXCLUDED.last_interaction,updated_at=NOW()",rel.CharacterID,rel.TargetID,rel.Affinity,rel.Trust,rel.Familiarity,rel.Interactions,rel.LastInteraction);if err!=nil{return err};_,err=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_social_events(character_id,target_id,event_type,affinity_delta,trust_delta,familiarity_delta,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",rel.CharacterID,rel.TargetID,"INTERACTION",4,2,5,"successful social interaction");return err}
