package store
import("context";"encoding/json";"time";"github.com/shido-ui/Worldbuster/backend/internal/simulation")
type SimulationMemoryRecord struct{ID string;CharacterID string;MemoryType string;TargetID string;Event string;Importance int;Sentiment int;CreatedAt time.Time}
type SimulationActionRecord struct{ID string;CharacterID string;ActionType string;TargetID string;DecisionScore int;Executed bool;CreatedAt time.Time}
type SimulationRepository struct{DB *DB}
func(r SimulationRepository)EnsureCharacter(ctx context.Context,c simulation.SimCharacter)error{personality,_:=json.Marshal(c.Personality);goals,_:=json.Marshal(c.Goals);_,err:=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_characters(character_id,name,controller_type,personality,goals,last_tick,active) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(character_id) DO UPDATE SET name=EXCLUDED.name,personality=EXCLUDED.personality,goals=EXCLUDED.goals,last_tick=EXCLUDED.last_tick,active=EXCLUDED.active",c.ID,c.Name,string(c.Controller),personality,goals,c.LastTick,c.Active);return err}
func(r SimulationRepository)RecordMemory(ctx context.Context,characterID string,m simulation.Memory)error{_,err:=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_character_memory(character_id,memory_type,target_id,event,importance,sentiment,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)",characterID,m.Type,m.TargetID,m.Event,m.Importance,m.Sentiment,time.Unix(m.CreatedAt,0));return err}
func(r SimulationRepository)RecordAction(ctx context.Context,characterID string,a simulation.Action,executed bool)error{_,err:=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_character_actions(character_id,action_type,target_id,decision_score,executed) VALUES($1,$2,$3,$4,$5)",characterID,string(a.Type),a.TargetID,a.Priority,executed);return err}
func(r SimulationRepository)RecordRelationship(ctx context.Context,rel simulation.Relationship)error{_,err:=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_relationships(character_id,target_id,affinity,trust,familiarity,interactions,last_interaction,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,NOW()) ON CONFLICT(character_id,target_id) DO UPDATE SET affinity=EXCLUDED.affinity,trust=EXCLUDED.trust,familiarity=EXCLUDED.familiarity,interactions=EXCLUDED.interactions,last_interaction=EXCLUDED.last_interaction,updated_at=NOW()",rel.FromID,rel.ToID,rel.Affinity,rel.Trust,rel.Familiarity,rel.Interactions,rel.LastInteraction);if err!=nil{return err};_,err=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_social_events(character_id,target_id,event_type,affinity_delta,trust_delta,familiarity_delta,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",rel.FromID,rel.ToID,"INTERACTION",4,2,5,"successful social interaction");return err}
func(r SimulationRepository)PropagateSocialReputation(ctx context.Context,characterID string,publicDelta,trustDelta int,reason string)error{_,err:=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_reputation(character_id) VALUES($1) ON CONFLICT(character_id) DO NOTHING",characterID);if err!=nil{return err};_,err=r.DB.SQL.ExecContext(ctx,"UPDATE simulated_reputation SET public_score=GREATEST(-1000,LEAST(1000,public_score+$2)),trust_score=GREATEST(-1000,LEAST(1000,trust_score+$3)),updated_at=NOW() WHERE character_id=$1",characterID,publicDelta,trustDelta);if err!=nil{return err};_,err=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_reputation_history(character_id,source,public_delta,trust_delta,reason) VALUES($1,$2,$3,$4,$5)",characterID,"SIMULATION",publicDelta,trustDelta,reason);return err}
func(r SimulationRepository)RecordEconomy(ctx context.Context,characterID string,e simulation.EconomicState)error{_,err:=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_economy(character_id,balance,lifetime_income,lifetime_spending,updated_at) VALUES($1,$2,$3,$4,NOW()) ON CONFLICT(character_id) DO UPDATE SET balance=EXCLUDED.balance,lifetime_income=EXCLUDED.lifetime_income,lifetime_spending=EXCLUDED.lifetime_spending,updated_at=NOW()",characterID,e.Balance,e.LifetimeIncome,e.LifetimeSpending);if err!=nil{return err};_,err=r.DB.SQL.ExecContext(ctx,"INSERT INTO simulated_economy_ledger(character_id,amount,balance_after,reason) VALUES($1,$2,$3,$4)",characterID,0,e.Balance,"simulation_state_sync");return err}
