package store

import ("context";"database/sql";"errors";"time")

var ErrInvalidSocialTarget = errors.New("invalid social target")
type RelationshipRecord struct { CharacterID string `json:"characterId"`; TargetID string `json:"targetId"`; Kind string `json:"kind"`; Score int `json:"score"`; UpdatedAt time.Time `json:"updatedAt"` }
type MessageRecord struct { ID string `json:"id"`; FromID string `json:"fromId"`; ToID string `json:"toId"`; Body string `json:"body"`; CreatedAt time.Time `json:"createdAt"`; ReadAt *time.Time `json:"readAt,omitempty"` }
type SocialRepository struct{DB *DB}
func(r SocialRepository) SetRelationship(ctx context.Context,from,to,kind string,score int)(RelationshipRecord,error){if from==""||to==""||from==to{return RelationshipRecord{},ErrInvalidSocialTarget};var x RelationshipRecord;err:=r.DB.SQL.QueryRowContext(ctx,"INSERT INTO relationships(character_id,target_id,kind,score,updated_at) VALUES($1,$2,$3,$4,NOW()) ON CONFLICT(character_id,target_id) DO UPDATE SET kind=EXCLUDED.kind,score=EXCLUDED.score,updated_at=NOW() RETURNING character_id::text,target_id::text,kind,score,updated_at",from,to,kind,score).Scan(&x.CharacterID,&x.TargetID,&x.Kind,&x.Score,&x.UpdatedAt);return x,err}
func(r SocialRepository) Relationship(ctx context.Context,from,to string)(RelationshipRecord,error){var x RelationshipRecord;err:=r.DB.SQL.QueryRowContext(ctx,"SELECT character_id::text,target_id::text,kind,score,updated_at FROM relationships WHERE character_id=$1 AND target_id=$2",from,to).Scan(&x.CharacterID,&x.TargetID,&x.Kind,&x.Score,&x.UpdatedAt);return x,err}
func(r SocialRepository) Send(ctx context.Context,from,to,body string)(MessageRecord,error){if from==""||to==""||from==to||body==""{return MessageRecord{},ErrInvalidSocialTarget};var m MessageRecord;err:=r.DB.SQL.QueryRowContext(ctx,"INSERT INTO messages(id,from_id,to_id,body) VALUES(gen_random_uuid(),$1,$2,$3) RETURNING id::text,from_id::text,to_id::text,body,created_at,read_at",from,to,body).Scan(&m.ID,&m.FromID,&m.ToID,&m.Body,&m.CreatedAt,&m.ReadAt);return m,err}
func(r SocialRepository) Inbox(ctx context.Context,to string)([]MessageRecord,error){rows,err:=r.DB.SQL.QueryContext(ctx,"SELECT id::text,from_id::text,to_id::text,body,created_at,read_at FROM messages WHERE to_id=$1 ORDER BY created_at DESC LIMIT 100",to);if err!=nil{return nil,err};defer rows.Close();out:=[]MessageRecord{};for rows.Next(){var m MessageRecord;if err:=rows.Scan(&m.ID,&m.FromID,&m.ToID,&m.Body,&m.CreatedAt,&m.ReadAt);err!=nil{return nil,err};out=append(out,m)};return out,rows.Err()}