ALTER TABLE player_profiles
 ADD COLUMN IF NOT EXISTS strength INTEGER NOT NULL DEFAULT 1 CHECK (strength >= 0),
 ADD COLUMN IF NOT EXISTS defense INTEGER NOT NULL DEFAULT 1 CHECK (defense >= 0),
 ADD COLUMN IF NOT EXISTS speed INTEGER NOT NULL DEFAULT 1 CHECK (speed >= 0),
 ADD COLUMN IF NOT EXISTS intelligence INTEGER NOT NULL DEFAULT 1 CHECK (intelligence >= 0),
 ADD COLUMN IF NOT EXISTS endurance INTEGER NOT NULL DEFAULT 1 CHECK (endurance >= 0);

CREATE INDEX IF NOT EXISTS idx_player_profiles_xp ON player_profiles(xp);
