import React,{useEffect,useMemo,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{AuthPanel}from"./auth";
import"./styles.css";

type Account={id:string;username:string};
type State={profile:{id?:string;locationId?:string;displayName:string;level:number;xp:number;cash:number;energy:number;strength:number;defense:number;speed:number;intelligence:number;endurance:number};economy:{balance:number;currency:string};inventory:{stacks:{itemId:string;quantity:number}[]}};
type World={tick:number;onlineCount:number;day:number;time:string;status:string};
type Job={id:string;name:string;department:string;baseSalary:number;requiredLevel:number;requiredStat:number;requiredEducation:number};
type Course={id:string;name:string;durationMinutes:number;educationGain:number;requiredLevel:number};
type EventItem={id:string;type:string;actorId:string;targetId?:string;createdAt:string;payload?:Record<string,unknown>};
type ConnectionStatus="LOADING"|"CONNECTED"|"AUTHENTICATION_REQUIRED"|"SERVER_ERROR"|"OFFLINE";
type Mission={id:string;code:string;title:string;description:string;missionType:string;minLevel:number;rewardCash:number;rewardXP:number;targetType:string;targetValue:number};
type PlayerMission={id:string;missionId:string;status:string;progress:number;acceptedAt:string;completedAt?:string};
type Asset={id:string;symbol?:string;name:string;currentPrice?:number};
type NewsItem={id:string;title:string;summary?:string;body?:string;publishedAt?:string};
type WorldEvent={id:string;type:string;title?:string;description?:string;createdAt?:string};
type Achievement={id:string;code?:string;name?:string;title?:string;description?:string;unlocked?:boolean;completed?:boolean;progress?:number;targetProgress?:number;points?:number};type RankingEntry={playerId?:string;displayName?:string;level?:number;wealth?:number;rank?:number};type LedgerEntry={id:string;amount:number;balanceAfter:number;reason:string;referenceId?:string;createdAt:string};
type Order={id:string;assetId:string;side:string;quantity:number;unitPrice:number;status?:string;isOwner?:boolean};
type Location={id:string;name?:string;description?:string};
type Route={from:string;to:string;travelSeconds:number};
type Travel={characterId:string;from:string;to:string;startedAt:string;arrivesAt:string};
type NotificationItem={id:string;type:string;title:string;body:string;createdAt:string;read?:boolean};type EquipmentItem={id:string;name:string;category?:string;slot?:string;requiredLevel?:number;powerBonus?:number;defenseBonus?:number;speedBonus?:number;durabilityMax?:number};type EquippedItem={playerId:string;slot:string;itemId:string;durability:number;equippedAt:string};type Relationship={targetId:string;familiarity:number;trust:number;affinity:number;interactions:number};type Territory={id:string;name?:string;description?:string;stability:number;controllerOrganizationId?:string;commerceModifierBPS?:number;safetyModifier?:number};type CombatRecord={id:string;attackerId:string;defenderId:string;winnerId?:string;rounds?:number;xpReward?:number;createdAt?:string};
const worldFallback:World={tick:0,onlineCount:0,day:1,time:"00:00",status:"CONNECTING"};
const staticCache=new Map<string,{expires:number;value:any}>();
async function cachedJSON<T>(url:string,signal?:AbortSignal,ttl=300000):Promise<T>{
 const hit=staticCache.get(url);
 if(hit&&hit.expires>Date.now())return hit.value as T;
 const value=await fetchJSON(url,{},signal) as T;
 staticCache.set(url,{expires:Date.now()+ttl,value});
 return value;
}

async function fetchJSON(url:string,init:RequestInit={},signal?:AbortSignal){
 const response=await fetch(url,{...init,credentials:"include",signal});
 const data=await response.json().catch(()=>null);
 if(!response.ok){const error=new Error(data?.error??"HTTP "+response.status);(error as any).status=response.status;throw error}
 return data;
}
const nav=["Overview","Character","Inventory","Equipment","Economy","World","Missions","Market","Jobs","Education","Social","Reputation","Organizations","Territory","Combat","Notifications","Achievements","News"];
const eventLabel=(e:EventItem)=>e.type.replaceAll("_"," ").toLowerCase().replace(/^./,c=>c.toUpperCase());
const formatTime=(value:string)=>{const d=new Date(value);return Number.isNaN(d.getTime())?"recent":d.toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})};

function AnimatedNumber({value}:{value:number}){const ref=useRef<HTMLSpanElement|null>(null);const previous=useRef(value);useEffect(()=>{const from=previous.current,to=value;previous.current=value;if(from===to||!ref.current)return;const start=performance.now();const duration=450;const frame=(now:number)=>{const p=Math.min(1,(now-start)/duration);const eased=1-Math.pow(1-p,3);if(ref.current)ref.current.textContent=Math.round(from+(to-from)*eased).toLocaleString();if(p<1)requestAnimationFrame(frame)};requestAnimationFrame(frame)},[value]);return <span ref={ref}>{value.toLocaleString()}</span>}

function App(){
 const[view,setView]=useState("Overview"),[combatHistory,setCombatHistory]=useState<CombatRecord[]>([]),[rankings,setRankings]=useState<RankingEntry[]>([]),[ledger,setLedger]=useState<LedgerEntry[]>([]),[rankingKind,setRankingKind]=useState("level"),[combatTarget,setCombatTarget]=useState(""),[combatBusy,setCombatBusy]=useState(false),[territories,setTerritories]=useState<Territory[]>([]),[territoryBusy,setTerritoryBusy]=useState(false),[selectedOrg,setSelectedOrg]=useState(""),[orgBusy,setOrgBusy]=useState(false),[orgReputations,setOrgReputations]=useState<Record<string,number>>({}),[equipmentItems,setEquipmentItems]=useState<EquipmentItem[]>([]),[equipped,setEquipped]=useState<EquippedItem[]>([]),[equipmentBusy,setEquipmentBusy]=useState(false),[relationshipTarget,setRelationshipTarget]=useState(""),[relationship,setRelationship]=useState<Relationship|null>(null),[messageTarget,setMessageTarget]=useState(""),[messageBody,setMessageBody]=useState(""),[socialBusy,setSocialBusy]=useState(false),[missions,setMissions]=useState<Mission[]>([]),[playerMissions,setPlayerMissions]=useState<PlayerMission[]>([]),[assets,setAssets]=useState<Asset[]>([]),[orders,setOrders]=useState<Order[]>([]),[selectedAsset,setSelectedAsset]=useState(""),[marketQuantity,setMarketQuantity]=useState(1),[marketPrice,setMarketPrice]=useState(1),[marketBusy,setMarketBusy]=useState(false),[news,setNews]=useState<NewsItem[]>([]),[worldEvents,setWorldEvents]=useState<WorldEvent[]>([]),[achievements,setAchievements]=useState<Achievement[]>([]),[locations,setLocations]=useState<Location[]>([]),[routes,setRoutes]=useState<Route[]>([]),[travel,setTravel]=useState<Travel|null>(null),[account,setAccount]=useState<Account|null>(null),[checking,setChecking]=useState(true),[world,setWorld]=useState(worldFallback),[state,setState]=useState<State|null>(null),[jobs,setJobs]=useState<Job[]>([]),[employment,setEmployment]=useState<Job|null>(null),[courses,setCourses]=useState<Course[]>([]),[training,setTraining]=useState<any>(null),[education,setEducation]=useState(0),[courseBusy,setCourseBusy]=useState(false),[jobBusy,setJobBusy]=useState(false),[message,setMessage]=useState(""),[inbox,setInbox]=useState<any[]>([]),[reputation,setReputation]=useState<any>(null),[organizations,setOrganizations]=useState<any[]>([]),[notifications,setNotifications]=useState<NotificationItem[]>([]),[events,setEvents]=useState<EventItem[]>([]),[connection,setConnection]=useState<ConnectionStatus>("LOADING"),[connectionError,setConnectionError]=useState(""),[mobileNav,setMobileNav]=useState(false),[missionBusy,setMissionBusy]=useState(false);
 const refreshSequence=useRef(0); const refreshAbort=useRef<AbortController|null>(null); const selectedAssetRef=useRef(""); const eventsLoaded=useRef(false);
 async function optional<T>(url:string,signal?:AbortSignal):Promise<T|null>{try{return await fetchJSON(url,{},signal) as T}catch(error){if((error as any)?.name==="AbortError")throw error;return null}}
 useEffect(()=>{if(!account||!selectedAsset)return;const controller=new AbortController();void optional<any>("/api/v1/market/orders?assetId="+encodeURIComponent(selectedAsset),controller.signal).then(data=>{if(!controller.signal.aborted)setOrders(data?.orders??[])}).catch(error=>{if((error as any)?.name!=="AbortError")setMessage((error as Error).message)});return()=>controller.abort()},[account,selectedAsset]);
 useEffect(()=>{if(!account)return;const source=new EventSource("/api/v1/events/stream");source.addEventListener("world",(event)=>{try{const item=JSON.parse((event as MessageEvent).data) as EventItem;setEvents(prev=>[...prev,item].slice(-20));setMessage("Live world event received.")}catch{}});source.onerror=()=>{setMessage("Live connection interrupted; retrying automatically.");};return()=>source.close()},[account]);
 const refresh=async()=>{
  const sequence=++refreshSequence.current;
  refreshAbort.current?.abort();
  const controller=new AbortController();
  refreshAbort.current=controller;
  const signal=controller.signal;
  try{
   const results=await Promise.all([
    fetchJSON("/api/v1/world",{},signal),fetchJSON("/api/v1/player/state",{},signal),fetchJSON("/api/v1/economy/history",{},signal),cachedJSON("/api/v1/jobs",signal),
    fetchJSON("/api/v1/jobs/status",{},signal),cachedJSON("/api/v1/education/courses",signal),fetchJSON("/api/v1/education/status",{},signal),
    fetchJSON("/api/v1/social/inbox",{},signal),fetchJSON("/api/v1/reputation",{},signal),fetchJSON("/api/v1/organizations",{},signal),
    eventsLoaded.current?Promise.resolve(null):fetchJSON("/api/v1/events?limit=20",{},signal),
    optional<any>("/api/v1/missions",signal),optional<any>("/api/v1/market/assets",signal),
    optional<any>("/api/v1/news?limit=12",signal),optional<any>("/api/v1/world-events",signal),optional<any>("/api/v1/achievements",signal),cachedJSON<any>("/api/v1/world/locations",signal),optional<any>("/api/v1/world/travel/current",signal),optional<any>("/api/v1/notifications",signal),optional<any>("/api/v1/equipment/items",signal),optional<any>("/api/v1/equipment",signal),optional<any>("/api/v1/territories",signal),optional<any>("/api/v1/combat/history",signal),optional<any>("/api/v1/rankings?id=level",signal)
   ]);
   if(sequence!==refreshSequence.current)return;
   const[w,s,economyData,j,e,coursesData,trainingData,si,rep,orgs,eventsData,missionData,assetData,newsData,worldEventData,achievementData,locationData,travelData,notificationData,equipmentData,equippedData,territoryData,combatData,rankingData]=results as any[];
   const availableAssets=(assetData?.assets??[]) as Asset[];
   const firstAsset=availableAssets[0];
   const preferredAsset=selectedAssetRef.current && availableAssets.some(a=>a.id===selectedAssetRef.current)?selectedAssetRef.current:firstAsset?.id||"";
   if(sequence!==refreshSequence.current||signal.aborted)return;
   setWorld(w);setState(s);setLedger(economyData?.ledger??[]);setJobs(j.jobs??j);setEmployment(e.job??null);setCourses(coursesData.courses??coursesData);
   setEducation(trainingData.education??0);setTraining(trainingData.training??null);setInbox(si.messages??[]);setReputation(rep);
   setOrganizations(orgs.organizations??orgs);setNotifications(notificationData?.notifications??(Array.isArray(notificationData)?notificationData:[]));if(eventsData){setEvents((Array.isArray(eventsData)?eventsData:(eventsData.events??[])).slice(-20));eventsLoaded.current=true;}setMissions(missionData?.missions??[]);setAssets(availableAssets);selectedAssetRef.current=preferredAsset;setSelectedAsset(preferredAsset);setNews(newsData?.news??[]);setWorldEvents(worldEventData?.events??[]);setAchievements(achievementData?.achievements??[]);setLocations(locationData?.locations??[]);setRoutes(locationData?.routes??[]);setTravel(travelData?.traveling?travelData.travel:null);
   setPlayerMissions(missionData?.playerMissions??[]);setEquipmentItems(equipmentData?.items??[]);setEquipped(equippedData?.equipment??[]);setTerritories(territoryData?.territories??[]);setCombatHistory(combatData?.history??combatData?.records??[]);setRankings(rankingData?.entries??[]);setConnection("CONNECTED");setConnectionError("");
  }catch(error){
   if((error as any)?.name==="AbortError")return;
   if(sequence!==refreshSequence.current)return;
   const status=(error as any)?.status;
   if(status===401){setAccount(null);setState(null);setConnection("AUTHENTICATION_REQUIRED");setConnectionError("Session expired. Please sign in again.")}
   else if(status>=500){setConnection("SERVER_ERROR");setConnectionError("World server is unavailable.")}
   else if(error instanceof TypeError){setConnection("OFFLINE");setConnectionError("Network connection unavailable.")}
   else{setConnection("SERVER_ERROR");setConnectionError((error as Error).message)}
  }finally{if(refreshAbort.current===controller)refreshAbort.current=null}
 };
 useEffect(()=>{let cancelled=false;fetchJSON("/api/v1/auth/me").then(data=>{if(!cancelled)setAccount({id:data.accountId,username:"PLAYER"})}).catch(error=>{if(!cancelled&&(error as any)?.status===401)setConnection("AUTHENTICATION_REQUIRED")}).finally(()=>{if(!cancelled)setChecking(false)});return()=>{cancelled=true}},[]);
 useEffect(()=>{eventsLoaded.current=false;selectedAssetRef.current="";setEvents([]);setOrders([]);setSelectedAsset("");if(!account)return;void refresh();const onVisibility=()=>{if(document.visibilityState==="visible")void refresh()};document.addEventListener("visibilitychange",onVisibility);const id=setInterval(()=>{if(document.visibilityState==="visible")void refresh()},30000);return()=>{document.removeEventListener("visibilitychange",onVisibility);refreshAbort.current?.abort();refreshAbort.current=null;clearInterval(id)}},[account]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();setView("Overview");document.getElementById("command-search")?.focus()}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
 const enroll=async(courseId:string)=>{setCourseBusy(true);try{const d=await fetchJSON("/api/v1/education/enroll",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({courseId})});setTraining(d.training);setMessage("Training started.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setCourseBusy(false)}};
 const hire=async(jobId:string)=>{setJobBusy(true);setMessage("");try{const d=await fetchJSON("/api/v1/jobs/employ",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId})});setEmployment(d.job);setMessage("Employment confirmed.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setJobBusy(false)}};
 const latestEvents=useMemo(()=>[...events].reverse().slice(0,6),[events]);
 const resolveCombat=async()=>{if(!combatTarget.trim())return;setCombatBusy(true);try{await fetchJSON("/api/v1/combat/resolve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({defenderId:combatTarget.trim()})});setMessage("Combat resolved by the server.");setCombatTarget("");await refresh()}catch(error){setMessage((error as Error).message)}finally{setCombatBusy(false)}};
 const joinOrganization=async(id:string)=>{setOrgBusy(true);try{await fetchJSON("/api/v1/organizations/join",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({organizationId:id,role:"member"})});setMessage("Organization membership confirmed.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setOrgBusy(false)}};
 const loadOrgReputation=async(id:string)=>{try{const d=await fetchJSON("/api/v1/organizations/reputation?organizationId="+encodeURIComponent(id));setOrgReputations(p=>({...p,[id]:Number(d.score??0)}))}catch(error){setMessage((error as Error).message)}};
 const addInfluence=async(territoryId:string,organizationId:string)=>{setTerritoryBusy(true);try{await fetchJSON("/api/v1/territories/influence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({territoryId,organizationId,delta:1,reason:"player territorial action"})});setMessage("Territory influence updated.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setTerritoryBusy(false)}};
 const equip=async(itemId:string)=>{setEquipmentBusy(true);try{await fetchJSON("/api/v1/equipment/equip",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId})});setMessage("Equipment changed.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setEquipmentBusy(false)}};
 const loadRelationship=async()=>{if(!relationshipTarget.trim())return;try{const d=await fetchJSON("/api/v1/social/relationship?targetId="+encodeURIComponent(relationshipTarget.trim()));setRelationship(d.relationship??null)}catch(error){setMessage((error as Error).message)}};
 const sendMessage=async()=>{if(!messageTarget.trim()||!messageBody.trim())return;setSocialBusy(true);try{await fetchJSON("/api/v1/social/send",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({toId:messageTarget.trim(),body:messageBody.trim()})});setMessage("Message sent.");setMessageBody("");await refresh()}catch(error){setMessage((error as Error).message)}finally{setSocialBusy(false)}};
 const acceptMission=async(id:string)=>{try{await fetchJSON("/api/v1/missions/accept",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({missionId:id})});setMessage("Mission accepted.");await refresh()}catch(error){setMessage((error as Error).message)}};
 if(checking)return <div className="auth-stage"><div className="boot"><div className="brand-mark">W</div><span>WORLDBUSTER</span><b>ESTABLISHING SECURE SESSION</b><div className="boot-line"/></div></div>;
 if(!account)return <div className="auth-stage"><AuthPanel onAuthenticated={setAccount}/></div>;
 const statusClass=connection.toLowerCase();
 return <div className="app">
  <header className="topbar"><button className="mobile-menu" aria-label="Open navigation" onClick={()=>setMobileNav(v=>!v)}>☰</button><div className="brand"><span className="brand-mark">W</span><span>WORLDBUSTER</span></div><div className={"world-status "+statusClass}><i/><span>{connection==="CONNECTED"?"LIVE WORLD":connection.replaceAll("_"," ")}</span><b>{connection==="CONNECTED"?"DAY "+world.day:"NO LIVE WORLD"}</b></div></header>
  <main className="game-shell">
   <aside className={"side "+(mobileNav?"open":"")}><div className="side-title">COMMAND</div>{nav.map(item=><button key={item} className={"nav "+(view===item?"active":"")} onClick={()=>{setView(item);setMobileNav(false)}}><span>{item}</span>{item==="Social"&&inbox.length>0&&<em>{inbox.length}</em>}</button>)}</aside>
   <section className="content">
    <div className="command-bar"><div className="kicker">PERSISTENT WORLD · {state?.profile.displayName??account.username}</div><label className="command-search"><span>⌕</span><input id="command-search" placeholder="Jump to a system…" onKeyDown={e=>{if(e.key==="Enter"){const q=e.currentTarget.value.toLowerCase();const hit=nav.find(x=>x.toLowerCase().includes(q));if(hit)setView(hit);e.currentTarget.value=""}}}/><kbd>/</kbd></label></div>
    {connection!=="CONNECTED"&&<div className={"status-banner "+statusClass}><i/><span>{connectionError||"Synchronizing with the authoritative server…"}</span><button onClick={()=>void refresh()}>RETRY</button></div>}
    {message&&<div className="toast" role="status">{message}<button onClick={()=>setMessage("")}>×</button></div>}
    <div className="title-row"><div><div className="kicker">COMMAND CENTER</div><h1>THE WORLD IS MOVING.</h1><p>Your state is authoritative. Actions create persistent consequences.</p></div><button className="sync" onClick={()=>void refresh()}><span>↻</span> SYNC</button></div>
    {state&&<section className="cards">
      <article className="metric"><span>LEVEL</span><strong><AnimatedNumber value={state.profile.level}/></strong><small>{state.profile.xp} XP</small></article>
      <article className="metric"><span>ENERGY</span><strong><AnimatedNumber value={state.profile.energy}/></strong><small>AVAILABLE</small></article>
      <article className="metric"><span>BALANCE</span><strong><AnimatedNumber value={state.economy.balance}/></strong><small>{state.economy.currency}</small></article>
      <article className="metric accent"><span>WORLD ONLINE</span><strong><AnimatedNumber value={world.onlineCount}/></strong><small>DAY {world.day} · TICK {world.tick}</small></article>
    </section>}
    {view==="Overview"&&state&&<><section className="dashboard-grid">
      <article className="panel hero-panel"><div className="panel-head"><span>WORLD CLOCK</span><small>SERVER AUTHORITY</small></div><div className="clock">{world.time}</div><div className="world-line"><span>DAY {world.day}</span><i/><span>TICK {world.tick}</span><i/><span>{world.status}</span></div></article>
      <article className="panel"><div className="panel-head"><span>CHARACTER</span><small>PROFILE</small></div><div className="profile-row"><div className="avatar">W</div><div><b>{state.profile.displayName}</b><small>Level {state.profile.level} · {state.profile.xp} XP</small></div></div><div className="mini-stats">{[["STR",state.profile.strength],["DEF",state.profile.defense],["SPD",state.profile.speed],["INT",state.profile.intelligence],["END",state.profile.endurance]].map(([k,v])=><div key={String(k)}><span>{k}</span><b>{v}</b></div>)}</div></article>
     </section><section className="dashboard-grid lower"><article className="panel"><div className="panel-head"><span>LIVE ACTIVITY</span><small>RECENT EVENTS</small></div><div className="timeline">{latestEvents.length?latestEvents.map(e=><div className="timeline-item event-enter" key={e.id}><i/><div><b>{eventLabel(e)}</b><small>{e.actorId||"world"} · {formatTime(e.createdAt)}</small></div><span className="event-pulse">LIVE</span></div>):<div className="empty"><b>No world events yet.</b><span>The event stream will appear here as the simulation moves.</span></div>}</div></article>
     <article className="panel"><div className="panel-head"><span>OPPORTUNITIES</span><small>YOUR STATE</small></div><div className="opportunity"><div><b>{employment?employment.name:"Find employment"}</b><span>{employment?employment.baseSalary.toLocaleString()+" WBX / cycle":"Career progression is available."}</span></div><button onClick={()=>setView("Jobs")}>{employment?"VIEW":"EXPLORE"}</button></div><div className="opportunity"><div><b>{training?training.courseName:"Continue education"}</b><span>{training?"Training in progress":"Build education and unlock roles."}</span></div><button onClick={()=>setView("Education")}>{training?"VIEW":"STUDY"}</button></div><div className="opportunity"><div><b>{inbox.length?inbox.length+" messages":"Social network"}</b><span>Relationships and reputation persist.</span></div><button onClick={()=>setView("Social")}>OPEN</button></div></article>
    </section></>}
    {view==="Missions"&&<Module title="MISSIONS" eyebrow="SERVER-AUTHORITATIVE OBJECTIVES">{playerMissions.length>0&&<div className="job-list">{playerMissions.map(pm=>{const m=missions.find(x=>x.id===pm.missionId);const target=Number(m?.targetValue??0);const ready=pm.status==="ACTIVE"&&target>0&&pm.progress>=target;return <div className="job" key={pm.id}><div><b>{m?.title??"Mission"}</b><small>{pm.status} · Progress {pm.progress}/{m?.targetValue??"?"}{m?` · Reward ${m.rewardXP} XP / ${m.rewardCash} WBX`:""}</small>{m&&<div className="mission-progress"><i style={{width:`${Math.min(100,(pm.progress/Math.max(1,target))*100)}%`}}/></div>}</div>{ready?<button disabled={missionBusy} onClick={async()=>{setMissionBusy(true);try{await fetchJSON("/api/v1/missions/complete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({missionId:pm.missionId})});setMessage("Mission completed.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setMissionBusy(false)}}}>COMPLETE</button>:<strong>{pm.status}</strong>}</div>})}</div>}{missions.length?<div className="job-list">{missions.filter(m=>!playerMissions.some(pm=>pm.missionId===m.id&&["ACTIVE","COMPLETED"].includes(pm.status))).map(m=><div className="job" key={m.id}><div><b>{m.title}</b><small>{m.description} · {m.missionType} · Reward {m.rewardXP} XP / {m.rewardCash} WBX</small></div><button onClick={()=>acceptMission(m.id)}>ACCEPT</button></div>)}</div>:<Empty title="No available missions" text="The world has no missions available for your current level."/>}</Module>}
    {view==="Market"&&<Module title="MARKET" eyebrow="LIVE ECONOMY">{assets.length?<><div className="job-list">{assets.map(a=><div className={"job "+(selectedAsset===a.id?"selected":"")} key={a.id} onClick={()=>{selectedAssetRef.current=a.id;setSelectedAsset(a.id)}}><div><b>{a.name}</b><small>{a.symbol??a.id} · Server-priced asset</small></div><strong>{a.currentPrice==null?"—":a.currentPrice.toLocaleString()} WBX</strong></div>)}</div><div className="market-selected"><span>SELECTED ASSET</span><b>{assets.find(a=>a.id===selectedAsset)?.name??"Choose an asset"}</b><strong>{assets.find(a=>a.id===selectedAsset)?.currentPrice?.toLocaleString()??"—"} WBX</strong></div><div className="market-order-panel"><div className="panel-head"><span>PLACE SELL ORDER</span><small>SERVER VALIDATED</small></div><div className="market-form"><label>Quantity<input type="number" min="1" value={marketQuantity} onChange={e=>setMarketQuantity(Math.max(1,Number(e.target.value)||1))}/></label><label>Unit price<input type="number" min="1" value={marketPrice} onChange={e=>setMarketPrice(Math.max(1,Number(e.target.value)||1))}/></label><button disabled={marketBusy||!selectedAsset} onClick={async()=>{setMarketBusy(true);try{await fetchJSON("/api/v1/market/sell",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetId:selectedAsset,quantity:marketQuantity,unitPrice:marketPrice})});setMessage("Sell order placed.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setMarketBusy(false)}}}>PLACE ORDER</button></div></div></>:<Empty title="Market unavailable" text="No market assets were returned by the authoritative server."/>}{orders.length>0&&<div className="item-list">{orders.slice(0,12).map(o=><div className="item" key={o.id}><div><b>{o.side} · {o.assetId}</b><small>{o.quantity} units · {o.unitPrice} / unit</small></div><span>{o.status||"OPEN"} {o.status==="OPEN"&&o.isOwner&&<button disabled={marketBusy} onClick={async e=>{e.stopPropagation();setMarketBusy(true);try{await fetchJSON("/api/v1/market/cancel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:o.id})});setMessage("Order cancelled.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setMarketBusy(false)}}}>CANCEL</button>} <button disabled={marketBusy||o.status==="FILLED"} onClick={async e=>{e.stopPropagation();setMarketBusy(true);try{await fetchJSON("/api/v1/market/buy",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderId:o.id,quantity:Math.min(marketQuantity,o.quantity)})});setMessage("Order purchased.");await refresh()}catch(error){setMessage((error as Error).message)}finally{setMarketBusy(false)}}}>BUY</button></span></div>)}</div>}</Module>}
    {view==="Notifications"&&<Module title="NOTIFICATIONS" eyebrow="WORLD SIGNALS"><div className="panel-head"><span>INBOX</span><button className="text-action" disabled={!notifications.some(n=>!n.read)} onClick={async()=>{try{await fetchJSON("/api/v1/notifications/read-all",{method:"POST"});await refresh()}catch(error){setMessage((error as Error).message)}}}>MARK ALL READ</button></div>{notifications.length?<div className="item-list">{notifications.map(n=><div className={"item notification-item "+(n.read?"read":"unread")} key={n.id}><span className="notification-dot" aria-hidden="true"/><div><b>{n.title}</b><small>{n.body} · {formatTime(n.createdAt)}</small></div>{!n.read&&<button className="text-action" onClick={async()=>{try{await fetchJSON("/api/v1/notifications/read?id="+encodeURIComponent(n.id),{method:"POST"});setNotifications(p=>p.map(x=>x.id===n.id?{...x,read:true}:x))}catch(error){setMessage((error as Error).message)}}}>READ</button>}</div>)}</div>:<Empty title="No notifications" text="World events addressed to your character will appear here."/>}</Module>}
    {view==="Combat"&&<Module title="COMBAT" eyebrow="SERVER-RESOLVED"><div className="social-compose"><div className="panel-head"><span>CHALLENGE PLAYER</span><small>SERVER AUTHORITY</small></div><div className="market-form social-form"><input aria-label="Defender player id" placeholder="Defender player ID" value={combatTarget} onChange={e=>setCombatTarget(e.target.value)}/><button disabled={combatBusy||!combatTarget.trim()} onClick={()=>void resolveCombat()}>{combatBusy?"RESOLVING…":"RESOLVE COMBAT"}</button></div></div><div className="panel-head"><span>COMBAT HISTORY</span><small>{combatHistory.length} RECENT</small></div>{combatHistory.length?<div className="item-list">{combatHistory.map(x=><div className="item" key={x.id}><div><b>{x.winnerId?"WINNER "+x.winnerId:"COMBAT "+x.id}</b><small>{x.attackerId} vs {x.defenderId}{x.createdAt?" · "+formatTime(x.createdAt):""}</small></div><strong>{x.xpReward??0} XP</strong></div>)}</div>:<Empty title="No combat records" text="Completed server-resolved fights will appear here."/>}</Module>}
    {view==="Achievements"&&<Module title="ACHIEVEMENTS" eyebrow="PROGRESSION"><div className="panel-head"><span>ACHIEVEMENT PROGRESS</span><small>{achievements.filter(a=>a.completed||a.unlocked).length}/{achievements.length} COMPLETE</small></div>{achievements.length?<div className="achievement-grid">{achievements.map(a=>{const p=Number(a.progress??(a.completed||a.unlocked?1:0)),t=Math.max(1,Number(a.targetProgress??1));return <div className="achievement-card" key={a.id}><div className="panel-head"><b>{a.title??a.name??a.code??a.id}</b><small>{a.points??0} PTS</small></div><p>{a.description??"Achievement progress"}</p><div className="progress-track"><span style={{width:`${Math.min(100,p/t*100)}%`}}/></div><small>{p} / {t}{a.completed||a.unlocked?" · COMPLETE":""}</small></div>})}</div>:<Empty title="No achievements" text="Progress milestones will appear here."/>}<div className="panel-head ranking-head"><span>LEVEL RANKING</span><button className="text-action" onClick={async()=>{try{const d=await fetchJSON("/api/v1/rankings?id="+encodeURIComponent(rankingKind));setRankings(d.entries??[])}catch(error){setMessage((error as Error).message)}}}>REFRESH</button></div>{rankings.length?<div className="item-list">{rankings.slice(0,10).map((x,i)=><div className="item" key={x.playerId??i}><div><b>#{x.rank??i+1} {x.displayName??x.playerId??"PLAYER"}</b><small>{rankingKind==="wealth"?`${x.wealth??0} wealth`:`Level ${x.level??0}`}</small></div></div>)}</div>:<Empty title="Ranking unavailable" text="No ranking entries are currently available."/>}</Module>}
    {view==="World"&&<Module title="WORLD" eyebrow="LIVE LOCATION NETWORK"><div className="map-grid">{locations.map(l=>{const current=state?.profile.locationId===l.id;const outgoing=routes.filter(r=>r.from===l.id);return <article className={"location-card "+(current?"current":"")} key={l.id}><div className="location-badge">{current?"YOU ARE HERE":"NODE"}</div><h3>{l.name??l.id}</h3><p>{l.description??"World location"}</p>{current&&travel&&<div className="travel-status">TRAVELING TO <b>{travel.to}</b></div>}{outgoing.map(r=><button className="route-action" key={r.to} disabled={!!travel||current===false&&state?.profile.locationId!==r.from} onClick={async()=>{try{await fetchJSON("/api/v1/world/travel",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({characterId:state?.profile.id,from:r.from,to:r.to})});setMessage("Travel started.");await refresh()}catch(error){setMessage((error as Error).message)}}}>TRAVEL → {locations.find(x=>x.id===r.to)?.name??r.to} · {r.travelSeconds}s</button>)}</article>})}</div>{travel&&<div className="travel-banner"><span>IN TRANSIT</span><b>{travel.from} → {travel.to}</b><small>Arrival {formatTime(travel.arrivesAt)}</small></div>}</Module>}
    {view==="Organizations"&&<Module title="ORGANIZATIONS" eyebrow="SOCIAL POWER NETWORK"><div className="job-list">{organizations.map(o=><div className="job org-card" key={o.id}><div><b>{o.name??o.id}</b><small>{o.description??"Organization"} · Reputation {orgReputations[o.id]??"—"}</small></div><div className="org-actions"><button onClick={()=>void loadOrgReputation(o.id)}>REPUTATION</button><button disabled={orgBusy} onClick={()=>void joinOrganization(o.id)}>JOIN</button></div></div>)}</div></Module>}
    {view==="News"&&<Module title="WORLD NEWS" eyebrow="PERSISTENT WORLD FEED">{news.length?<div className="job-list">{news.map(n=><article className="job" key={n.id}><div><b>{n.title}</b><small>{n.summary??n.body??"World report"}{n.publishedAt?" · "+formatTime(n.publishedAt):""}</small></div></article>)}</div>:<Empty title="No news" text="The world press has no reports available yet."/>}{worldEvents.length>0&&<><div className="panel-head" style={{marginTop:24}}><span>WORLD EVENTS</span><small>{worldEvents.length} RECENT</small></div><div className="timeline">{worldEvents.slice(0,8).map(e=><div className="timeline-item" key={e.id}><i/><div><b>{e.title??e.type}</b><small>{e.description??e.type}{e.createdAt?" · "+formatTime(e.createdAt):""}</small></div></div>)}</div></>}</Module>}
     {view==="Character"&&state&&<Module title="CHARACTER" eyebrow="AUTHORITATIVE PROFILE">
      <div className="character-head"><div className="avatar large">W</div><div><h2>{state.profile.displayName}</h2><p>Level {state.profile.level} · {state.profile.xp} XP</p></div></div>
      <div className="large-stats">{[["Strength",state.profile.strength],["Defense",state.profile.defense],["Speed",state.profile.speed],["Intelligence",state.profile.intelligence],["Endurance",state.profile.endurance]].map(([k,v])=><div className="large-stat" key={String(k)}><span>{k}</span><strong>{v}</strong><div className="stat-bar"><i style={{width:Math.min(100,Number(v))+"%"}} /></div></div>)}</div>
     </Module>}
    {view==="Inventory"&&state&&<Module title="INVENTORY" eyebrow="PERSISTENT ITEMS">{state.inventory.stacks.length?<div className="item-list">{state.inventory.stacks.map(x=><div className="item" key={x.itemId}><div><b>{x.itemId}</b><small>Persistent item stack</small></div><strong>x{x.quantity}</strong></div>)}</div>:<Empty title="Inventory is empty" text="Items acquired through the world will appear here."/>}</Module>}
    {view==="Equipment"&&state&&<Module title="EQUIPMENT" eyebrow="LOADOUT + DURABILITY"><div className="equipment-grid"><div><div className="panel-head"><span>AVAILABLE</span><small>{equipmentItems.length} DEFINITIONS</small></div><div className="job-list">{equipmentItems.map(item=>{const active=equipped.some(x=>x.itemId===item.id);return <div className={"job "+(active?"selected":"")} key={item.id}><div><b>{item.name}</b><small>{item.slot??item.category??"ITEM"} · Req L{item.requiredLevel??1} · +{item.powerBonus??0} POW / +{item.defenseBonus??0} DEF / +{item.speedBonus??0} SPD</small></div><button disabled={equipmentBusy||active||((state?.profile.level??0)<(item.requiredLevel??1))} onClick={()=>equip(item.id)}>{active?"EQUIPPED":((state?.profile.level??0)<(item.requiredLevel??1)?"LOCKED":"EQUIP")}</button></div>})}</div></div><div><div className="panel-head"><span>ACTIVE LOADOUT</span><small>{equipped.length} SLOTS</small></div>{equipped.length?<div className="item-list">{equipped.map(x=><div className="item" key={x.slot}><div><b>{x.slot}</b><small>{x.itemId} · Equipped {formatTime(x.equippedAt)}</small></div><strong>{x.durability} DUR</strong></div>)}</div>:<Empty title="Nothing equipped" text="Equip available items to build your loadout."/>}</div></div></Module>}
    {view==="Economy"&&state&&<Module title="ECONOMY" eyebrow={state.economy.currency}><div className="economy-total">{state.economy.balance.toLocaleString()}<small>{state.economy.currency}</small></div><div className="economy-note">Balances and ledger entries are server-authoritative.</div><div className="panel-head economy-ledger-head"><span>RECENT LEDGER</span><small>{ledger.length} ENTRIES</small></div>{ledger.length?<div className="item-list">{ledger.slice(0,20).map(x=><div className="item" key={x.id}><div><b>{x.reason}</b><small>{formatTime(x.createdAt)}{x.referenceId?" · "+x.referenceId:""}</small></div><strong className={x.amount>=0?"ledger-credit":"ledger-debit"}>{x.amount>=0?"+":""}{x.amount.toLocaleString()} WBX</strong></div>)}</div>:<Empty title="No transactions yet" text="Authoritative economy activity will appear here."/>}</Module>}
    {view==="Jobs"&&<Module title="CAREER MARKET" eyebrow="PERSISTENT WORLD">{employment&&<div className="employment-banner"><span>EMPLOYED</span><b>{employment.name}</b><small>{employment.department} · {employment.baseSalary.toLocaleString()} WBX / cycle</small></div>}{jobs.length?<div className="job-list">{jobs.map(j=><div className="job" key={j.id}><div><b>{j.name}</b><small>{j.department} · Level {j.requiredLevel}+ · {j.requiredStat} total stats · Education {j.requiredEducation}+</small></div><div className="job-action"><strong>{j.baseSalary.toLocaleString()} WBX</strong><button disabled={!!employment||jobBusy||((state?.profile.level??0)<j.requiredLevel)} onClick={()=>hire(j.id)}>{employment?"EMPLOYED":((state?.profile.level??0)<j.requiredLevel?"LOCKED":"HIRE")}</button></div></div>)}</div>:<Empty title="No jobs available" text="The career market has no currently listed positions."/>}</Module>}
    {view==="Education"&&<Module title="ACADEMY" eyebrow={"EDUCATION "+education}>{training&&<div className="employment-banner"><span>IN TRAINING</span><b>{training.courseName}</b><small>Completes {new Date(training.completesAt).toLocaleString()}</small></div>}<div className="job-list">{courses.map(c=><div className="job" key={c.id}><div><b>{c.name}</b><small>{c.durationMinutes} min · +{c.educationGain} education · Level {c.requiredLevel}+</small></div><button disabled={!!training||courseBusy||((state?.profile.level??0)<c.requiredLevel)} onClick={()=>enroll(c.id)}>{training?"TRAINING":((state?.profile.level??0)<c.requiredLevel?"LOCKED":"ENROLL")}</button></div>)}</div></Module>}
    {view==="Social"&&<Module title="SOCIAL NETWORK" eyebrow="PERSISTENT"><div className="social-compose"><div className="panel-head"><span>DIRECT MESSAGE</span><small>SERVER VALIDATED</small></div><div className="market-form social-form"><input aria-label="Recipient player id" placeholder="Recipient player ID" value={messageTarget} onChange={e=>setMessageTarget(e.target.value)}/><input aria-label="Message" placeholder="Write a message…" value={messageBody} onChange={e=>setMessageBody(e.target.value)} maxLength={2000}/><button disabled={socialBusy||!messageTarget.trim()||!messageBody.trim()} onClick={()=>void sendMessage()}>{socialBusy?"SENDING…":"SEND"}</button></div></div><div className="social-compose"><div className="panel-head"><span>RELATIONSHIP LOOKUP</span><small>PLAYER CONTEXT</small></div><div className="market-form social-form"><input aria-label="Relationship target" placeholder="Target player ID" value={relationshipTarget} onChange={e=>setRelationshipTarget(e.target.value)}/><button onClick={()=>void loadRelationship()}>LOOK UP</button></div>{relationship&&<div className="relationship-grid"><b>FAMILIARITY <strong>{relationship.familiarity}</strong></b><b>TRUST <strong>{relationship.trust}</strong></b><b>AFFINITY <strong>{relationship.affinity}</strong></b><b>INTERACTIONS <strong>{relationship.interactions}</strong></b></div>}</div><div className="item-list">{inbox.length?inbox.map(m=><div className="item" key={m.id}><div><b>Message from {m.fromId}</b><small>{new Date(m.createdAt).toLocaleString()}</small></div><span>OPEN</span></div>):<Empty title="No messages" text="Social events and messages will appear here."/>}</div></Module>}
    {view==="Reputation"&&<Module title="REPUTATION" eyebrow="CONSEQUENCES">{reputation?<><div className="large-stats compact">{[["Public",reputation.publicScore],["Trust",reputation.trustScore],["Notoriety",reputation.notorietyScore]].map(([k,v])=><div className="large-stat" key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="section-note">Public reputation, trust and notoriety are server-maintained consequences. Social interactions and world simulation can change them.</div></>:<Empty title="Reputation unavailable" text="No reputation data was returned by the server."/>}</Module>}
    {view==="Territory"&&<Module title="TERRITORY" eyebrow="FACTION INFLUENCE"><div className="territory-grid">{territories.length?territories.map(t=><article className="territory-card" key={t.id}><div className="panel-head"><span>{t.name??t.id}</span><small>STABILITY {t.stability}</small></div><p>{t.description??"Contested world territory."}</p><div className="territory-meta"><span>CONTROL {t.controllerOrganizationId??"NONE"}</span><span>COMMERCE {(t.commerceModifierBPS??0)/100}%</span><span>SAFETY {t.safetyModifier??0}</span></div>{selectedOrg&&<button disabled={territoryBusy} onClick={()=>void addInfluence(t.id,selectedOrg)}>+ INFLUENCE</button>}</article>):<Empty title="No territories" text="The world has not exposed territorial data yet."/>}</div><div className="section-note">Influence changes require authenticated organization membership and are resolved by the server.</div></Module>}
   </section>
  </main>
 </div>;
}
function Module({title,eyebrow,children}:{title:string;eyebrow:string;children:React.ReactNode}){return <section className="panel module"><div className="panel-head"><span>{title}</span><small>{eyebrow}</small></div>{children}</section>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><b>{title}</b><span>{text}</span></div>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);

